CREATE TABLE School (
	[Id] INT IDENTITY(1,1) NOT NULL,
	[Name] NVARCHAR(50) NOT NULL,
	[Address] NVARCHAR(200) NOT NULL,
	[Phone] CHAR(10) NOT NULL,
	CONSTRAINT [PK_School] PRIMARY KEY CLUSTERED ([Id] ASC),
);
